#!/bin/bash
# script to build thunderbirddata.tar.xz after an update
# must be run in /home/robert
cd /home/robert
tar --xz --exclude=.thunderbird/06g73ld3.default-release/ImapMail -cvf thunderbirdconfig.tar.xz .thunderbird
