#!/bin/sh
##################################################
# configdata:postinst
##################################################

# this script only runs during configure.
# if $1 is not equal to configure, exit
test "$1" = "configure" || exit 0;

# add repository for thunderbird
add-apt-repository ppa:mozillateam/ppa

# prioritise PPA over snap
echo "Package: thunderbird*
Pin: release o=LP-PPA-mozillateam
Pin-Priority: 1001

Package: thunderbird*
Pin: release o=Ubuntu
Pin-Priority: -1" > /etc/apt/preferences.d/mozillateamppa

# to avoid snap taking over automatic updates
echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";' > /etc/apt/apt.conf.d/51unattended-upgrades-thunderbird


# xz-utils is required for untarring
# apt install also does not work here

# /home/robert/thunderbirddata.tar.xz must be extracted
cd /home/robert
sudo -u robert tar --overwrite --xz -xvf thunderbirddata.tar.xz

# remove the file
rm -v /home/robert/thunderbirddata.tar.xz
rm -v /home/robert/buildthdata
rm -v /home/robert/xtractthdata
