#!/bin/sh
##################################################
# configdata:postinst
##################################################

# this script only runs during configure.
# if $1 is not equal to configure, exit
test "$1" = "configure" || exit 0;

echo "========================================================"
echo "thunderbirdconfig:postinst"
echo "========================================================"

# add repository for thunderbird if it does not exist
test -f /etc/apt/sources.list.d/mozillateam-ubuntu-ppa*.sources || add-apt-repository ppa:mozillateam/ppa -y

# prioritise PPA over snap
if test ! -f /etc/apt/preferences.d/mozillateamppa; then
	echo "Package: thunderbird*
Pin: release o=LP-PPA-mozillateam
Pin-Priority: 1001

Package: thunderbird*
Pin: release o=Ubuntu
Pin-Priority: -1" > /etc/apt/preferences.d/mozillateamppa
fi

# to avoid snap taking over automatic updates
if test ! -f /etc/apt/apt.conf.d/51unattended-upgrades-thunderbird; then
	echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";' > /etc/apt/apt.conf.d/51unattended-upgrades-thunderbird
fi

# xz-utils is required for untarring
# apt install also does not work here

# /home/robert/thunderbirdconfig.tar.xz must be extracted
# thunderbirdconfig.tar.xz  must not contain any emails including no local folders
# since these will overwrite existing emails during installation
cd /home/robert
sudo -u robert tar --overwrite --xz -xf thunderbirdconfig.tar.xz

# remove the file
rm -v /home/robert/thunderbirdconfig.tar.xz
rm -v /home/robert/buildthdata
rm -v /home/robert/xtractthdata

# install thunderbird after time delay
# so lock is released first
echo "============================================================="
echo "Installing thunderbird and thunderbird-locale-en in 5 seconds"
echo "============================================================="
(sleep 5; apt install thunderbird thunderbird-locale-en -y) &
